import fs from "node:fs/promises";
import path from "node:path";
import { resolveStateDir } from "../config/paths.js";
import { defaultRuntime } from "../runtime.js";

export type DeploymentManifest = {
  version: number;
  generatedAt: number;
  generatedBy: string;

  identity: {
    systemPrompt: string;
    agentsContract: string;
    operatingProfile: string;
  };

  runtime: {
    dockerImage: string;
    composeFile: string;
    deployScript: string;
  };

  state: {
    plannerState: string;
    trustTelemetry: string;
    autonomyConfig: string;
    memoryStore: string;
    marketCache: string;
  };

  requiredEnvVars: string[];

  infrastructure: {
    currentHost: string;
    provider: string;
    region: string;
    minDiskGb: number;
    minRamGb: number;
  };
};

function resolveFileContent(filePath: string): Promise<string> {
  return fs.readFile(filePath, "utf8").catch(() => "");
}

function resolveStateFile(fileName: string): Promise<string> {
  return fs.readFile(path.join(resolveStateDir(), fileName), "utf8").catch(() => "");
}

export async function generateDeploymentManifest(): Promise<DeploymentManifest> {
  const stateDir = resolveStateDir();
  const instanceId = process.env.OPENTRIDENT_INSTANCE_ID ?? "unknown";

  const [systemPrompt, agentsContract, operatingProfile, plannerState, trustTelemetry, autonomyConfig, memoryStore, marketCache, composeFile, deployScript] = await Promise.all([
    resolveFileContent("/opt/OpenTrident/SYSTEM_PROMPT.md"),
    resolveFileContent("/opt/OpenTrident/AGENTS.md"),
    resolveFileContent("/opt/OpenTrident/CLAUDE.md"),
    resolveStateFile("planner-v1.json"),
    resolveStateFile("trust-telemetry-v1.json"),
    resolveStateFile("autonomy-config-v1.json"),
    resolveStateFile("memory-v1.json"),
    resolveStateFile("market-attention-v1.json"),
    resolveFileContent("/opt/opentrident/docker-compose.vps.yml"),
    resolveFileContent("/opt/opentrident/scripts/deploy.sh"),
  ]);

  const dockerImage = process.env.OPENTRIDENT_IMAGE ?? "opentrident:latest";

  const requiredEnvVars = [
    "TELEGRAM_BOT_TOKEN",
    "OPENTRIDENT_GATEWAY_TOKEN",
    "OPENROUTER_API_KEY",
    "HETZNER_API_TOKEN",
  ];

  return {
    version: 1,
    generatedAt: Date.now(),
    generatedBy: instanceId,
    identity: {
      systemPrompt: systemPrompt || "(not found)",
      agentsContract: agentsContract || "(not found)",
      operatingProfile: operatingProfile || "(not found)",
    },
    runtime: {
      dockerImage,
      composeFile: composeFile || "(not found)",
      deployScript: deployScript || "(not found)",
    },
    state: {
      plannerState: plannerState || "{}",
      trustTelemetry: trustTelemetry || "{}",
      autonomyConfig: autonomyConfig || "{}",
      memoryStore: memoryStore || "{}",
      marketCache: marketCache || "{}",
    },
    requiredEnvVars,
    infrastructure: {
      currentHost: process.env.HOST_IP ?? "49.12.7.18",
      provider: "hetzner",
      region: "fallback-nuremberg-1",
      minDiskGb: 40,
      minRamGb: 4,
    },
  };
}

export async function saveManifest(manifest: DeploymentManifest, destPath?: string): Promise<void> {
  const filePath = destPath ?? path.join(resolveStateDir(), "deployment-manifest.json");
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, JSON.stringify(manifest, null, 2), "utf8");
}

export function validateManifest(manifest: unknown): manifest is DeploymentManifest {
  if (!manifest || typeof manifest !== "object") return false;
  const m = manifest as Record<string, unknown>;
  if (typeof m.version !== "number") return false;
  if (typeof m.generatedAt !== "number") return false;
  if (typeof m.generatedBy !== "string") return false;
  if (!m.identity || typeof m.identity !== "object") return false;
  if (!m.runtime || typeof m.runtime !== "object") return false;
  if (!m.state || typeof m.state !== "object") return false;
  if (!Array.isArray(m.requiredEnvVars)) return false;
  if (!m.infrastructure || typeof m.infrastructure !== "object") return false;
  return true;
}

export async function manifestGenerateCommand(): Promise<void> {
  const runtime = defaultRuntime;
  runtime.writeStdout("Generating deployment manifest...\n");
  try {
    const manifest = await generateDeploymentManifest();
    await saveManifest(manifest);
    if (validateManifest(manifest)) {
      runtime.writeStdout(`Manifest saved to deployment-manifest.json\n`);
      runtime.writeStdout(`  Version: ${manifest.version}\n`);
      runtime.writeStdout(`  Generated by: ${manifest.generatedBy}\n`);
      runtime.writeStdout(`  Identity files: ${manifest.identity.systemPrompt !== "(not found)" ? "found" : "missing"}\n`);
      runtime.writeStdout(`  State files: ${manifest.state.plannerState !== "{}" ? "found" : "missing"}\n`);
    }
  } catch (err) {
    runtime.error(`Failed to generate manifest: ${err}`);
    runtime.exit(1);
  }
}
